algoritmo "Exercicio10"
// Função :
// Autor :
// Data : 24/03/2019
// Seção de Declarações 
var
Ndep, SB, VH, HT, VL: real

inicio
escreval ("resultado do valor bruto e valor liquido")
escreval ("digite o Ndep")
leia(Ndep)
escreval ("digite valor hora")
leia(VH)
escreval ("digite horas tabaiadas")
leia(HT)
SB<- VH*HT
VL<-(Ndep*300)+SB
escreval ("o valor do salário bruto e:" , SB)
escreval ("o valor liquido e:" , VL)



// Seção de Comandos 
fimalgoritmo
