algoritmo "exercicio11"
// Função :
// Autor :
// Data : 24/03/2019
// Seção de Declarações 
var
CM, M, DM, MM: real
inicio
escreval("medida em centimetros")
escreval ("digite os valor em Centimetros")
leia (CM)
M<- CM/100
DM<- CM/10
MM<- CM*10
escreval ("o valor em metros é:" , M)
escreval ("o valor em decimetros é:" , DM)
escreval ("o valor em milimetros é:" , MM)




// Seção de Comandos 
fimalgoritmo
