algoritmo "semnome"
// Função :
// Autor :
// Data : 25/03/2019
// Seção de Declarações 
var
peso, NP, PA: real
inicio
escreval ("digite o peso atual")
leia (peso)

PA<- peso+(peso*0.15)
NP<- peso-(peso*0.20)

escreval("o novo peso se a pessoa engrodar 15% sobre o peso digitado é:", NP)
escreval("o novo peso se a pessoa emagrecer 20% sobre o peso digitado é:", PA)

// Seção de Comandos 
fimalgoritmo
